### ISSUE TITLE
Lost 2 hours of life on this

### ISSUE THREAD

**Issue by theraphim** [orrc/jenkins-filepath-untar#1]
Greetings.

(writing here because it's convenient).

This is purely a file content issue. I don't know what triggers it though, but I know that go1.7.3 as downloaded breaks even if I load it from file:///... - but if I extract and repack it it's all good.
So I'm guessing next step is to grab the archive and try reading it through the file reader jenkins uses

**Comment by orrc** [comment]
This comment would be better added to the issue linked from this repo: [JENKINS-34742](https://issues.jenkins-ci.org/browse/JENKINS-34742).
